/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vehicles.ui;

import com.mycompany.vehicles.Vehicle.Motocycle;
import com.mycompany.vehicles.Vehicle.PickUp;
import com.mycompany.vehicles.Vehicle.Sedan;
import com.mycompany.vehicles.Vehicle.Vehicle;
import java.util.LinkedList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author marl8n
 */
public class Vehicles extends javax.swing.JFrame {
    
    
    Integer c = 0;
    LinkedList<Vehicle> vehicles = new LinkedList<Vehicle>();
    ButtonGroup btnGroup = new ButtonGroup();
    

    /**
     * Creates new form Vehicles
     */
    public Vehicles() {
        btnGroup.add(radioButtonAdd);
        btnGroup.add(radioButtonEdit);
        btnGroup.add(radioButtonSearch);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonAdd = new javax.swing.JRadioButton();
        radioButtonEdit = new javax.swing.JRadioButton();
        radioButtonSearch = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioButtonAdd.setText("Agregar");

        radioButtonEdit.setText("Editar");

        radioButtonSearch.setText("Buscar");

        jTextField1.setEnabled(false);

        jTextField2.setEnabled(false);

        jTextField3.setEnabled(false);

        jTextField4.setEnabled(false);

        jTextField5.setEnabled(false);

        jTextField6.setEnabled(false);

        jTextField7.setEnabled(false);

        jTextField8.setEnabled(false);

        jLabel1.setText("Placa");

        jLabel2.setText("Modelo");

        jLabel3.setText("Marca");

        jLabel4.setText(" ");

        jLabel5.setText(" ");

        jLabel6.setText(" ");

        jLabel7.setText(" ");

        jLabel8.setText(" ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Pickup", "Motocicleta", "Camión", "Camioneta" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jLabel9.setText("Selecciona el vehiculo");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(radioButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(radioButtonSearch)))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonAdd)
                    .addComponent(radioButtonEdit)
                    .addComponent(radioButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        if (jComboBox1.getSelectedItem().equals("Sedan"))
        {
            setLabelsCar();
        }
        else if (jComboBox1.getSelectedItem().equals("Pickup"))
        {
            setLabelsCar();
        }
        else if (jComboBox1.getSelectedItem().equals("Motocicleta"))
        {
            setLabelsMotocycle();
        }
        else if (jComboBox1.getSelectedItem().equals("Camión"))
        {
            setLabelsTruck();
        }
        else if (jComboBox1.getSelectedItem().equals("Camioneta"))
        {
            setLabelsAutobus();
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jButton1.getText().equals("Agregar"))
            addVehicle();
        else if(jButton1.getText().equals("Buscar"))
            searchByLicensePlate();
        else if(jButton1.getText().equals("Editar"))
            editVehicle();
    }//GEN-LAST:event_jButton1MouseClicked

    private void setLabelsCar(){
        jLabel1.setText("Placa");
        jLabel2.setText("Modelo");
        jLabel3.setText("Marca");
        jLabel4.setText("Motor");
        jLabel5.setText("Gasolina");
        jLabel6.setText("Numero de puertas");
        jLabel7.setText("Numero de pasajeros");
        jLabel8.setText("Kilometros recorridos");
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField5.setEnabled(true);
        jTextField6.setEnabled(true);
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(true);
    }
    
    private void setLabelsMotocycle(){
        jLabel1.setText("Placa");
        jLabel2.setText("Modelo");
        jLabel3.setText("Marca");
        jLabel4.setText("Motor");
        jLabel5.setText("cc Motor");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField5.setEnabled(true);
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
    }
    
    private void setLabelsTruck(){
        jLabel1.setText("Placa");
        jLabel2.setText("Modelo");
        jLabel3.setText("Marca");
        jLabel4.setText("Motor");
        jLabel5.setText("Tipo de Gasolina");
        jLabel6.setText("Toneladas que carga");
        jLabel7.setText("");
        jLabel8.setText("");
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField5.setEnabled(true);
        jTextField6.setEnabled(true);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
    }
    
    private void setLabelsAutobus(){
        jLabel1.setText("Placa");
        jLabel2.setText("Modelo");
        jLabel3.setText("Marca");
        jLabel4.setText("Motor");
        jLabel5.setText("Tipo de Gasolina");
        jLabel6.setText("Numero de pasajeros");
        jLabel7.setText("");
        jLabel8.setText("");
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField5.setEnabled(true);
        jTextField6.setEnabled(true);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
    }
    
    
    
    private void setTextFieldsUnabled(){
        jLabel1.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
    }
    
    private void setLabelsByRadioButton(){
        if (radioButtonAdd.isSelected())
        {
            jComboBox1.setEnabled(true);
        }
        else if (radioButtonEdit.isSelected())
        {
            jComboBox1.setEnabled(false);
            setTextFieldsUnabled();
        }
        else if (radioButtonSearch.isSelected())
        {
            jComboBox1.setEnabled(false);
            setTextFieldsUnabled();
        }
    }
    
    private void searchByLicensePlate(){
        String buffer = jTextField1.getText();
        Integer idx = -1;
        for (int i = 0; i < c; i++ )
        {
            if (vehicles.get(i).getLicensePlate().equals(buffer))
            {
                idx = i;
                break;
            }
        }
        if ( idx >= 0 )
        {
            JOptionPane.showMessageDialog(rootPane, vehicles.get(idx).getInfo());
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "No hemos encontrado la placa " + buffer + " en nuestra base de datos.");
        }
    }
    
    private void addVehicle(){
        if (jComboBox1.getSelectedItem().equals("Sedan"))
        {
            addSedan();
        }
        else if (jComboBox1.getSelectedItem().equals("Pickup"))
        {
            addPickup();
        }
        else if (jComboBox1.getSelectedItem().equals("Motocicleta"))
        {
            addMotocycle();
        }
        else if (jComboBox1.getSelectedItem().equals("Camión"))
        {
            addTruck();
        }
        else if (jComboBox1.getSelectedItem().equals("Camioneta"))
        {
            addAutobus();
        }
    }
    
    private void addSedan(){
        vehicles.add(new Sedan(
                Integer.valueOf(jLabel7.getText()),
                Integer.valueOf(jLabel6.getText()),
                jLabel4.getText(),
                jLabel5.getText(),
                Integer.valueOf(jLabel8.getText()),
                jLabel1.getText(),
                jLabel2.getText(),
                jLabel3.getText()
                
        ));
        
    }
    
    private void addPickup()
    {
        vehicles.add(new PickUp(
                Integer.valueOf(jLabel7.getText()),
                Integer.valueOf(jLabel6.getText()),
                jLabel4.getText(),
                jLabel5.getText(),
                Integer.valueOf(jLabel8.getText()),
                jLabel1.getText(),
                jLabel2.getText(),
                jLabel3.getText()
                
        ));
        
    }
    
    private void addMotocycle(){
        
        //ccmotor, motor, licensePlate, model, brand
        vehicles.add(new Motocycle(
                jTextField5.getText(),
                jTextField4.getText(),
                jTextField1.getText(),
                jTextField2.getText(),
                jTextField3.getText()
        ));
        
    }
    
    private void editVehicle(){
        if (!jTextField1.getText().isEmpty())
        {
            Integer idx = -1;
            String buffer = jTextField1.getText();
            for ( int i = 0; i < c; i++ )
            {
                if (vehicles.get(i).getLicensePlate().equals(buffer)){
                    idx = i;
                    break;
                }
            }
            if (idx >= 0)
            {
                if (vehicles.get(idx).getClass().is){
                
            }
            }
        }
    }
    
    //
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JRadioButton radioButtonAdd;
    private javax.swing.JRadioButton radioButtonEdit;
    private javax.swing.JRadioButton radioButtonSearch;
    // End of variables declaration//GEN-END:variables
}
